//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WenceyWang.Richman4L.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WenceyWang.Richman4L.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.2.
        /// </summary>
        internal static string GovermentControlMax {
            get {
                return ResourceManager.GetString("GovermentControlMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -0.2.
        /// </summary>
        internal static string GovermentControlMin {
            get {
                return ResourceManager.GetString("GovermentControlMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.1.
        /// </summary>
        internal static string GovermentControlPower {
            get {
                return ResourceManager.GetString("GovermentControlPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.5.
        /// </summary>
        internal static string StockMarketMovementMax {
            get {
                return ResourceManager.GetString("StockMarketMovementMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -0.5.
        /// </summary>
        internal static string StockMarketMovementMin {
            get {
                return ResourceManager.GetString("StockMarketMovementMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.2.
        /// </summary>
        internal static string StockMarketMovementPower {
            get {
                return ResourceManager.GetString("StockMarketMovementPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string StockMovementMax {
            get {
                return ResourceManager.GetString("StockMovementMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.0.
        /// </summary>
        internal static string StockMovementMin {
            get {
                return ResourceManager.GetString("StockMovementMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.7.
        /// </summary>
        internal static string StockMovementPower {
            get {
                return ResourceManager.GetString("StockMovementPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60.
        /// </summary>
        internal static string TimeOfFall {
            get {
                return ResourceManager.GetString("TimeOfFall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60.
        /// </summary>
        internal static string TimeOfSpring {
            get {
                return ResourceManager.GetString("TimeOfSpring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60.
        /// </summary>
        internal static string TimeOfSummer {
            get {
                return ResourceManager.GetString("TimeOfSummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60.
        /// </summary>
        internal static string TimeOfWinter {
            get {
                return ResourceManager.GetString("TimeOfWinter", resourceCulture);
            }
        }
    }
}
